version: "2.4"

services:
  question:
    image: peerprep/question:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    platform: linux/amd64
  user:
    image: peerprep/user:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    platform: linux/amd64
    environment:
      - QUESTION_SERVICE_DEPLOYED_URL=http://question:8081
  collab:
    image: peerprep/collab:latest
    restart: unless-stopped
    ports:
      - 5005:5005
    platform: linux/amd64
    environment:
      - QUESTION_SERVICE_DEPLOYED_URL=http://question:8081
  comm:
    image: peerprep/comm:latest
    restart: unless-stopped
    ports:
      - 7000:7000
    platform: linux/amd64
