# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QuestionService CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_HOST: localhost
  DB_PORT: 27017
  DB_NAME: QuestionDB
  NODE_DOCKER_PORT: 8081
  ENV: development
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./QuestionService
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['5.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./QuestionService/yarn.lock
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - run: yarn install
    - run: yarn test
